# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: raj
  password: Raj@123
  database: Staffvault_database
  host: localhost

development:
  <<: *default
  database: Staffvault_development

test:
  <<: *default
  database: Staffvault_test

production:
  <<: *default
  database: Staffvault_production
  username: staffvault
  password: <%= ENV["Staffvault_DATABASE_PASSWORD"] %>

